---
title: "Lotto"
---

## Get 5 latest lotto numbers

```{r}
if (!require("rvest")) install.packages("rvest")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("dplyr")) install.packages("dplyr")

library(rvest)
library(ggplot2)
library(dplyr)

```

Crawl Numbers

```{r}
get_lotto_numbers <- function(draw_number) {
  url <- paste0("https://www.dhlottery.co.kr/gameResult.do?method=byWin&drwNo=", draw_number)
  webpage <- read_html(url)
  
  main_numbers <- webpage %>%
    html_nodes(".nums .num.win span.ball_645") %>%
    html_text() %>%
    as.numeric()

  bonus_number <- webpage %>%
    html_nodes(".nums .num.bonus span.ball_645") %>%
    html_text() %>%
    as.numeric()

  Sys.sleep(2)  
  return(c(main_numbers, bonus_number))
}
```

Save as dataset

```{r}
latest_draw_number <- 1124 

lotto_data <- lapply((latest_draw_number-4):latest_draw_number, get_lotto_numbers)
lotto_data <- do.call(rbind, lapply(lotto_data, matrix, ncol = 7, byrow = TRUE))
colnames(lotto_data) <- c(paste("Number", 1:6, sep=""), "Bonus")

```

Visualization

```{r}
number_counts <- as.data.frame(table(unlist(lotto_data)))
colnames(number_counts) <- c("Number", "Frequency")

ggplot(number_counts, aes(x = Number, y = Frequency, fill = Frequency)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Frequency of Lotto Numbers Including Bonus", x = "Number", y = "Frequency")


```
